import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Navbar } from '@/components/page-components'
const inter = Inter({ subsets: ['latin'] })
import {Toasters, Footer} from '@/components/page-components'

export const metadata: Metadata = {
  title: 'SOFF',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex min-h-screen flex-col`}>
        <Navbar />
        {children}
        <Toasters />
        <Footer />
      </body>
    </html>
  )
}
