import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Navbar } from '@/components/page-components'
const inter = Inter({ subsets: ['latin'] })
import { Footer } from '@/components/page-components'
import { SwrContextProvider, AuthContextProvider, NextAuthContext } from '@/context'
import {Toaster} from '@/components/ui/toaster'
export const metadata: Metadata = {
  title: 'SOFF',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={``}>
        <NextAuthContext>
          <AuthContextProvider>
            <SwrContextProvider>
              {children}  
              <Toaster /> 
            </SwrContextProvider>
          </AuthContextProvider>
        </NextAuthContext>
      </body>
    </html>
  )
}
