export * from './columns';
export * from './head-table';
export * from './header-module';
export * from './receipt';
export * from './saludo';
export * from './see-detail';
export * from './table-component';
export * from './table/DataTable';
export * from './upload-file';
